### ISSUE TITLE
Enable Image upload

### ISSUE THREAD

**Issue by eugenesinamban** [reservation-hub/reshub#94]
# Gist

Image upload is not enabled. There is no server / online storage for it.

## What's done

None

## What needs work

The whole implementation

- [ ] server / online storage
- [ ] how do we upload stuff using typescript

**Comment by sabi1125** [comment]
where are we going to save the images in ?????
what type of images are we talking about here are we talking about profile pictures and pictures for shops ?
if so dont we need to cap the number of images that can be uploaded ??
